# Generated by Django 5.1.5 on 2025-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('idsAuthor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('idGutendex', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('cover', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkToBook', models.URLField()),
                ('downloadCount', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='book.author')),
            ],
        ),
    ]
