# Generated by Django 5.1.5 on 2025-02-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_wordoccurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='idGutendex',
            field=models.IntegerField(unique=True),
        ),
    ]
