# Generated by Django 5.1.5 on 2025-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_idgutendex'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoccurrence',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
