# Generated by Django 5.1.5 on 2025-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_wordoccurrence_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordoccurrence',
            old_name='word',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='wordoccurrence',
            old_name='weight',
            new_name='term_frequency',
        ),
        migrations.AlterUniqueTogether(
            name='wordoccurrence',
            unique_together={('term', 'book')},
        ),
        migrations.AddField(
            model_name='wordoccurrence',
            name='tfidf_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
